; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui -MinimizeBox -MaximizeBox  +AlwaysOnTop  +Owner
Gui Font, s9, Segoe UI
Gui Add, Button, x0 y0 w80 h23, 98900423

Gui Show, x5122 y505 w81 h23
Return

GuiSize:
    If (A_EventInfo == 1) {
        Return
    }

Return

GuiContextMenu:
Return

GuiEscape:
GuiClose:
    ExitApp
