; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

---------------------------
Planet Version 6
---------------------------
Ny  vognløb: 31204 031123 Statistikgruppe:ÅRH_GV_0US


---------------------------
OK   
---------------------------

---------------------------
Planet Version 6
---------------------------
Ny  vognløb:  3302 031123 Statistikgruppe:ÅRH_VO_2US


---------------------------
OK   
---------------------------



vl := []

+^e::
{ 
    Gui repl: Font, s9, Segoe UI
    Gui repl: Add, ListBox, x78 y21 w120 h364 vvalg Choose1, %vl_liste%
    Gui repl: Add, Button, x359 y239 w80 h23 Default gguiok, &OK
    Gui repl: Add, Button, x359 y270 w80 h23 gguislet, &Slet
    Gui repl: Show, w620 h420, Window
    return
}

^e::
{
InputBox, vl_input
if ErrorLevel = 1
    return
vl.Push(vl_input)

vl_liste := ""
for k, v in vl
    vl_liste .= vl[k] . "|"
}
; vl_liste := vl_liste . "|"
; MsgBox, , , % vl_liste
Gui repl: Font, s9, Segoe UI
Gui repl: Add, ListBox, x78 y21 w120 h364 vvalg Choose1, %vl_liste%
Gui repl: Add, Button, x359 y239 w80 h23 Default gguiok, &OK
Gui repl: Add, Button, x359 y270 w80 h23 gguislet, &Slet
Gui repl: Show, w620 h420, Window
Return

GuisletEscape:
GuisletClose:
    ExitApp

GuiOK:
Gui, Submit
gui Destroy
MsgBox, , , % valg
return

Guislet:
Gui, Submit
gui Destroy
for k, v in vl
    if (valg = v)
        vl.Pop(k)
return

; Gui Show, w620 h420, Window
; ---------------------------
; Planet Version 6
; ---------------------------
; Ny  vognløb: 31240 301023 Statistikgruppe:ÅRH_GV_5OS


; ---------------------------
; OK   
; ---------------------------
