; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

tlf := "98900423"
tlf_knap := SubStr(tlf, 1, 4) . " " . SubStr(tlf, 5, 4)
SysGet, primær_skærm, monitorPrimary
; MsgBox, , , % primær_skærm, 

Gui tlf: +Labeltlf
Gui tlf: -MinimizeBox -MaximizeBox  +AlwaysOnTop  +Owner -Caption +ToolWindow +hwndhGui
Gui tlf: Font, s12, Segoe UI
Gui tlf: Add, Button, vtlfKopi gtlfKopi x0 y0 w120 h23, Tlf: %tlf_knap%

Gui tlf: Show, x995 y3 w120 h23 NA, Tlf
Return

GuiSize:


GuiContextMenu:
Return

GuiEscape:
GuiClose:
    ExitApp

+e::
{
    if WinExist("Tlf" , "", "", "")
        gui tlf: hide
    Else
        gui tlf: show, NA
    return
}

^e::
{
    ; global tlf_knap
    ; global tlf

    ; SendInput, +!k
    ; tlf := "test
    tlf := "12345678"
    tlf_knap := SubStr(tlf, 1, 4) . " " . SubStr(tlf, 5, 4)
    
    sleep 100
    GuiControl, tlf:text, Button1, Tlf: %tlf_knap% 
    return
}

tlfKopi:
{
    Clipboard := tlf
    return
}
